export const LOAD_APPOINTMENTS = 'LOAD_APPOINTMENTS'
export const ADD_APPOINTMENT = 'ADD_APPOINTMENT'
export const TOGGLE_APPOINTMENT = 'TOGGLE_APPOINTMENT'
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT'